Repository ReCoded-Org/capstone-istanbul-juniper, pull requests merged in 2020-11, with the labels that each got.

#25 Memory game initial card state generation
  package-lock.json
  package.json
  src/App.jsx
  src/components/memorygame/cardInitialStateGenerator.jsx
  src/components/memorygame/memoryCardBackSideImages.jsx
  src/components/memorygame/shuffle.jsx
  src/containers/MemoryGame/__snapshots__/index.test.js.snap
  src/containers/MemoryGame/index.css
  src/containers/MemoryGame/index.jsx
  src/containers/MemoryGame/index.test.js
  src/images/memoryGame/acidRain.svg
  src/images/memoryGame/airPollution.svg
  src/images/memoryGame/alternateEnergy.svg
  src/images/memoryGame/chemicalWaste.svg
  src/images/memoryGame/deforestation.svg
  src/images/memoryGame/globalWarming.svg
  src/images/memoryGame/greenhouseEffect.svg
  src/images/memoryGame/littering.svg
  src/images/memoryGame/meltingIceCaps.svg
  src/images/memoryGame/ozoneHole.svg
  src/images/memoryGame/recycle.svg
  src/images/memoryGame/waterPollution.svg
Labels: enhancement

#50 Image puzzle game - PuzzleGameContainer component
  src/components/PuzzleGameContainer/__snapshots__/index.test.js.snap
  src/components/PuzzleGameContainer/index.css
  src/components/PuzzleGameContainer/index.jsx
  src/components/PuzzleGameContainer/index.test.js
  src/images/puzzleGame/habitat.jpg
Labels: enhancement

#29 Memory game game card component
  package.json
  src/components/memorygame/MemoryGameCards/index.css
  src/components/memorygame/MemoryGameCards/index.jsx
  src/components/memorygame/MemoryGameFactList/__snapshots__/index.test.js.snap
  src/components/memorygame/MemoryGameFactList/index.css
  src/components/memorygame/MemoryGameFactList/index.jsx
  src/components/memorygame/MemoryGameFactList/index.test.js
  src/components/memorygame/cardInitialStateGenerator.jsx
  src/containers/MemoryGame/__snapshots__/index.test.js.snap
  src/containers/MemoryGame/index.jsx
  src/containers/MemoryGame/index.test.js
  src/images/memoryGameFrontImage.png
  src/images/memoryGameSuccessSymbol.svg
  src/locales/ar.json
  src/locales/en.json
  src/locales/tr.json
  yarn.lock
Labels: enhancement

#44 question component added
  src/components/QuizGameQuestions/index.css
  src/components/QuizGameQuestions/index.jsx
Labels: enhancement

#43 created questions api component
  src/components/QuizGameApi/index.jsx
Labels: enhancement

#42 Quiz game component
  src/components/QuizGame/__snapshots__/index.test.js.snap
  src/components/QuizGame/index.css
  src/components/QuizGame/index.jsx
  src/components/QuizGame/index.test.js
Labels: enhancement

#56 memory game fact list refactored
  src/components/memorygame/MemoryGameFactList/__snapshots__/index.test.js.snap
  src/components/memorygame/MemoryGameFactList/index.css
  src/components/memorygame/MemoryGameFactList/index.jsx
  src/components/memorygame/MemoryGameFactList/index.test.js
Labels: enhancement

#58 Memory game how to play and scroll to facts components
  src/components/memorygame/MemoryGameQuestionMarkIcon/index.css
  src/components/memorygame/MemoryGameQuestionMarkIcon/index.jsx
  src/components/memorygame/MemoryGameScrollToFacts/index.css
  src/components/memorygame/MemoryGameScrollToFacts/index.jsx
Labels: enhancement

#57 memory game flippable card
  src/components/memorygame/MemoryGameFlippableCard/index.css
  src/components/memorygame/MemoryGameFlippableCard/index.jsx
Labels: enhancement

#59 memory game success card and app.jsx update
  package.json
  src/App.jsx
  src/components/memorygame/MemoryGameSuccessCard/index.css
  src/components/memorygame/MemoryGameSuccessCard/index.jsx
  src/locales/ar.json
  src/locales/en.json
  src/locales/tr.json
Labels: enhancement

#60 memory game changeCardStatePropToOpposite function
  src/components/memorygame/gameHelpers.jsx
  src/components/memorygame/shuffle.jsx
Labels: enhancement

#64 Memory game cards
  src/components/memorygame/MemoryGameCards/index.css
  src/components/memorygame/MemoryGameCards/index.jsx
  yarn.lock
Labels: enhancement

#62 Memory game board
  src/App.jsx
  src/components/memorygame/MemoryGameBoard/index.css
  src/components/memorygame/MemoryGameBoard/index.jsx
  src/containers/MemoryGame/index.css
  src/containers/MemoryGame/index.jsx
Labels: enhancement

#61 memory game container and confetti config files
  package.json
  src/App.jsx
  src/components/memorygame/MemoryGameBoard/index.jsx
  src/components/memorygame/MemoryGameFactList/index.jsx
  src/components/memorygame/MemoryGameQuestionMarkIcon/index.jsx
  src/components/memorygame/MemoryGameScrollToFacts/index.jsx
  src/components/memorygame/confettiConfig.js
  src/containers/MemoryGame/index.css
  src/containers/MemoryGame/index.jsx
Labels: enhancement

#68 Puzzle keys fix
  src/components/PuzzleGameContainer/index.jsx
Labels: bug

#54 Games page image grid
  src/App.jsx
  src/components/gamespage/GamesPageImageGrid/__snapshots__/index.test.js.snap
  src/components/gamespage/GamesPageImageGrid/index.css
  src/components/gamespage/GamesPageImageGrid/index.jsx
  src/components/gamespage/GamesPageImageGrid/index.test.js
  src/containers/GamesPage/index.css
  src/containers/GamesPage/index.jsx
  src/containers/Home/index.jsx
  src/images/mockDestinyPoster.jpg
  src/images/mockGTAPoster.jpg
  src/images/mockZeldaPoster.jpg
  src/locales/ar.json
  src/locales/en.json
  src/locales/tr.json
Labels: enhancement

#66 About page - Main component
  package.json
  src/App.jsx
  src/components/ContactUsForm/__snapshots__/index.test.js.snap
  src/components/ContactUsForm/index.css
  src/components/ContactUsForm/index.jsx
  src/components/ContactUsForm/index.test.js
  src/components/PuzzleGameContainer/index.jsx
  src/components/gamespage/GamesPageImageGrid/__snapshots__/index.test.js.snap
  src/components/gamespage/GamesPageImageGrid/index.css
  src/components/gamespage/GamesPageImageGrid/index.jsx
  src/components/gamespage/GamesPageImageGrid/index.test.js
  src/components/memorygame/MemoryGameBoard/index.css
  src/components/memorygame/MemoryGameBoard/index.jsx
  src/components/memorygame/MemoryGameCards/index.css
  src/components/memorygame/MemoryGameCards/index.jsx
  src/components/memorygame/MemoryGameFactList/index.jsx
  src/components/memorygame/MemoryGameQuestionMarkIcon/index.jsx
  src/components/memorygame/MemoryGameScrollToFacts/index.jsx
  src/components/memorygame/confettiConfig.js
  src/containers/AboutPage/__snapshots__/index.test.js.snap
  src/containers/AboutPage/index.css
  src/containers/AboutPage/index.jsx
  src/containers/AboutPage/index.test.js
  src/containers/GamesPage/index.css
  src/containers/GamesPage/index.jsx
  src/containers/Home/index.jsx
  src/containers/MemoryGame/index.css
  src/containers/MemoryGame/index.jsx
  src/containers/MemoryGamePage/index.css
  src/containers/MemoryGamePage/index.jsx
  src/images/aboutPage/kid-1.png
  src/images/aboutPage/kid-2.png
  src/images/mockDestinyPoster.jpg
  src/images/mockGTAPoster.jpg
  src/images/mockZeldaPoster.jpg
  src/locales/ar.json
  src/locales/en.json
  src/locales/tr.json
  yarn.lock
Labels: enhancement

#69 adding container to quiz game
  src/App.jsx
  src/containers/QuizGamePage/__snapshots__/index.test.js.snap
  src/containers/QuizGamePage/index.css
  src/containers/QuizGamePage/index.jsx
  src/containers/QuizGamePage/index.test.js
Labels: enhancement

#65 Games page progress section
  src/App.jsx
  src/components/gamespage/GamesPageProgressSection/index.css
  src/components/gamespage/GamesPageProgressSection/index.jsx
  src/containers/GamesPage/index.jsx
  src/locales/ar.json
  src/locales/en.json
  src/locales/tr.json
Labels: enhancement

#76 Games page container
  src/components/gamespage/GamesPageProgressSection/__snapshots__/index.test.js.snap
  src/components/gamespage/GamesPageProgressSection/index.test.js
  src/containers/GamesPage/__snapshots__/index.test.js.snap
  src/containers/GamesPage/index.jsx
  src/containers/GamesPage/index.test.js
  src/images/gameScreenshots/matchingGame.svg
  src/images/gameScreenshots/memoryGame.svg
  src/images/gameScreenshots/puzzleGame.svg
  src/images/gameScreenshots/quizGame.svg
  src/images/world.svg
Labels: enhancement

#85 profile page added
  src/auth/authContext.jsx
  src/components/ProfilePage/index.css
  src/components/ProfilePage/index.jsx
  src/containers/ProfilePageContainer/index.jsx
  src/images/profilePage/profilePageImg.png
  src/locales/ar.json
  src/locales/en.json
  src/locales/tr.json
Labels: enhancement

#112 debug quiz game
  src/components/QuizGame/index.css
Labels: bug

#99 passwordReset component
  src/components/userauth/ResetPassword/__snapshots__/index.test.js.snap
  src/components/userauth/ResetPassword/index.css
  src/components/userauth/ResetPassword/index.jsx
  src/components/userauth/ResetPassword/index.test.js
Labels: enhancement

#100 debug the home page header section
  src/components/HomePageHeaderSection/__snapshots__/index.test.js.snap
  src/components/HomePageHeaderSection/index.css
  src/components/HomePageHeaderSection/index.jsx
  src/components/HomePageHeaderSection/index.test.js
  src/locales/ar.json
  src/locales/en.json
  src/locales/tr.json
Labels: bug

#116 Games page progress section fix
  src/components/gamespage/GamesPageProgressSection/__snapshots__/index.test.js.snap
  src/components/gamespage/GamesPageProgressSection/index.css
  src/components/gamespage/GamesPageProgressSection/index.jsx
  src/components/gamespage/GamesPageProgressSection/index.test.js
  src/containers/GamesPage/__snapshots__/index.test.js.snap
  src/containers/GamesPage/index.jsx
  src/containers/GamesPage/index.test.js
  src/locales/ar.json
  src/locales/en.json
  src/locales/tr.json
Labels: bug

#84 About page - final PR #37
  src/App.jsx
  src/components/MemberCard/__snapshots__/index.test.js.snap
  src/components/MemberCard/index.css
  src/components/MemberCard/index.jsx
  src/components/MemberCard/index.test.js
  src/components/TeamCards/__snapshots__/index.test.js.snap
  src/components/TeamCards/index.css
  src/components/TeamCards/index.jsx
  src/components/TeamCards/index.test.js
  src/containers/AboutPage/__snapshots__/index.test.js.snap
  src/containers/AboutPage/index.jsx
  src/locales/ar.json
  src/locales/en.json
  src/locales/tr.json
Labels: enhancement

#109 Footer route issue
  src/components/Footer/index.jsx
  src/components/Footer/index.test.jsx
Labels: invalid

#108 route to puzzle game
  src/App.jsx
Labels: invalid

#120 Fix: Games Page Image Grid
  src/components/gamespage/GamesPageImageGrid/__snapshots__/index.test.js.snap
  src/components/gamespage/GamesPageImageGrid/index.css
  src/components/gamespage/GamesPageImageGrid/index.jsx
  src/containers/GamesPage/__snapshots__/index.test.js.snap
  src/containers/GamesPage/index.jsx
  src/images/gameImages/memoryGame.svg
  src/images/gameImages/puzzleGame.svg
  src/images/gameImages/quizGame.svg
  src/images/gameScreenshots/matchingGame.svg
  src/images/gameScreenshots/memoryGame.svg
  src/images/gameScreenshots/puzzleGame.svg
  src/images/gameScreenshots/quizGame.svg
Labels: bug

#121 fixing the styling when switching to Arabic page
  src/App.css
  src/components/HomePageHeaderSection/__snapshots__/index.test.js.snap
  src/components/HomePageHeaderSection/index.css
  src/components/HomePageHeaderSection/index.jsx
  src/locales/ar.json
Labels: bug

#127 Fix memory game question mark size
  src/components/memorygame/MemoryGameBoard/index.css
  src/components/memorygame/MemoryGameBoard/index.jsx
  src/components/memorygame/MemoryGameQuestionMarkIcon/index.css
Labels: bug

#122 Fix Games Page
  src/components/gamespage/GamesPageImageGrid/index.css
  src/components/gamespage/GamesPageProgressSection/__snapshots__/index.test.js.snap
  src/components/gamespage/GamesPageProgressSection/index.jsx
  src/containers/GamesPage/__snapshots__/index.test.js.snap
Labels: bug

#123 Fix contact form responsiveness
  src/components/ContactUsForm/__snapshots__/index.test.js.snap
  src/components/ContactUsForm/index.css
  src/components/ContactUsForm/index.test.js
Labels: bug

#126 Fix ContactUsBottom responsive settings
  src/components/ContactUsBottom/index.css
Labels: bug

#128 Fix Memory game responsive font and layout
  src/components/memorygame/MemoryGameCards/index.jsx
  src/components/memorygame/MemoryGameFlippableCard/index.css
  src/components/memorygame/MemoryGameSuccessCard/index.css
Labels: bug

#133 Footer alignment
  src/components/Footer/index.css
Labels: bug

#136 Turkish translation fixes
  src/locales/tr.json
Labels: bug

#135 English translation fixes
  src/locales/en.json
Labels: bug

#129 Fix Footer background color
  src/components/Footer/__snapshots__/index.test.jsx.snap
  src/components/Footer/index.css
  src/components/Footer/index.jsx
Labels: bug

#138 Fix font
  src/App.css
  src/components/Navbar/index.css
  src/components/gamespage/GamesPageProgressSection/index.css
  src/components/userauth/Login/index.css
  src/components/userauth/Login/index.jsx
  src/containers/ResourcesPage/index.css
Labels: enhancement

#131 About page fix
  src/components/TeamCards/__snapshots__/index.test.js.snap
  src/components/TeamCards/index.jsx
  src/containers/AboutPage/__snapshots__/index.test.js.snap
  src/containers/AboutPage/index.css
  src/containers/AboutPage/index.jsx
  src/locales/ar.json
  src/locales/en.json
  src/locales/tr.json
Labels: enhancement

#134 Puzzle description
  src/components/PuzzlePageContent/__snapshots__/index.test.js.snap
  src/components/PuzzlePageContent/index.css
  src/components/PuzzlePageContent/index.jsx
  src/components/QuizGame/index.css
  src/containers/PuzzlePage/__snapshots__/index.test.js.snap
  src/locales/ar.json
  src/locales/en.json
  src/locales/tr.json
Labels: enhancement

#143 Fix navbar icons and dropdown alignment
  package.json
  src/components/Navbar/__snapshots__/index.test.js.snap
  src/components/Navbar/index.css
  src/components/Navbar/index.jsx
  yarn.lock
Labels: enhancement
